### ISSUE TITLE
ImportError: No module named 'inflection'

### ISSUE THREAD

**Issue by johnhillescobar** [quandl/quandl-python#101]
Hi.

I tried to import quandl but I received this Traceback error: "**ImportError: No module named 'inflection**'"  I reviewed your folder and found no file called inflection.py.

**This is the message detail:**

Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    import quandl
  File "C:\Python35\lib\site-packages\quandl\__init__.py", line 7, in <module>
    from .model.database import Database
  File "C:\Python35\lib\site-packages\quandl\model\database.py", line 11, in <module>
    from quandl.connection import Connection
  File "C:\Python35\lib\site-packages\quandl\connection.py", line 5, in <module>
    from .util import Util
  File "C:\Python\Python35\lib\site-packages\quandl\util.py", line 1, in <module>
    from inflection import parameterize
ImportError: No module named 'inflection

**Comment by mbasset** [comment]
Hi @johnhillescobar,

Can you give us more information about how you installed python and our plugin? `Inflection` should be installed as a dependency.

**Comment by mbasset** [comment]
HI @johnhillescobar ,

We haven't heard back from you. If this issue is still a problem please feel free to re-open and send us more information about your installation.

**Comment by Yarah24** [comment]
I am having the same issue. I installed quandl with "pip install quandl" in cmd
then in my .py file in PyCharm I do an import on quandl
then I use df = quandl.get("WIKI/AMZN")
and get the following logging:

Traceback (most recent call last):
  File "C:/Users/Gebruiker/.PyCharmEdu2018.1/config/scratches/scratch_2.py", line 1, in <module>
    import quandl
  File "C:\Users\Gebruiker\PycharmProjects\trackers\venv\lib\site-packages\quandl\__init__.py", line 7, in <module>
    from .model.database import Database
  File "C:\Users\Gebruiker\PycharmProjects\trackers\venv\lib\site-packages\quandl\model\database.py", line 11, in <module>
    from quandl.connection import Connection
  File "C:\Users\Gebruiker\PycharmProjects\trackers\venv\lib\site-packages\quandl\connection.py", line 5, in <module>
    from .util import Util
  File "C:\Users\Gebruiker\PycharmProjects\trackers\venv\lib\site-packages\quandl\util.py", line 1, in <module>
    from inflection import parameterize
ModuleNotFoundError: No module named 'inflection'

Process finished with exit code 1

Seems like there is missing a module.

**Comment by sneddonisaac** [comment]
I am also getting this: 
Traceback (most recent call last):
  File "/Users/isaac/Work/Code/new.py", line 3, in <module>
    import quandl
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/__init__.py", line 7, in <module>
    from .model.database import Database
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/model/database.py", line 5, in <module>
    import quandl.model.dataset
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/model/dataset.py", line 1, in <module>
    from quandl.operations.get import GetOperation
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/operations/get.py", line 1, in <module>
    from inflection import singularize
ImportError: No module named inflection
