### ISSUE TITLE
ImportError: No module named 'inflection

### ISSUE THREAD

**Issue by johnhillescobar** [quandl/quandl-python#102]
Hi.

I tried to import quandl but I received this Traceback error: "**ImportError: No module named 'inflection**'"  I reviewed your folder and found no file called inflection.py.

**This is the message detail:**

Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    import quandl
  File "C:\Python35\lib\site-packages\quandl\__init__.py", line 7, in <module>
    from .model.database import Database
  File "C:\Python35\lib\site-packages\quandl\model\database.py", line 11, in <module>
    from quandl.connection import Connection
  File "C:\Python35\lib\site-packages\quandl\connection.py", line 5, in <module>
    from .util import Util
  File "C:\Python\Python35\lib\site-packages\quandl\util.py", line 1, in <module>
    from inflection import parameterize
ImportError: No module named 'inflection

**Comment by mbasset** [comment]
Hi @johnhillescobar,

I am going to close this issue as you seem to have opened a duplicate.
