### ISSUE TITLE
ImportError: No module named inflection

### ISSUE THREAD

**Issue by sneddonisaac** [quandl/quandl-python#161]
Currently getting this whenever I try and run?

Traceback (most recent call last):
  File "/Users/isaac/Work/Code/new.py", line 3, in <module>
    import quandl
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/__init__.py", line 7, in <module>
    from .model.database import Database
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/model/database.py", line 5, in <module>
    import quandl.model.dataset
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/model/dataset.py", line 1, in <module>
    from quandl.operations.get import GetOperation
  File "/Library/Python/2.7/site-packages/Quandl-3.5.2-py2.7.egg/quandl/operations/get.py", line 1, in <module>
    from inflection import singularize
ImportError: No module named inflection

**Comment by couture-ql** [comment]
Hi there,

Quand 3.x series is only available for python 3.  Please take a look at our [deprecation notice](https://github.com/quandl/quandl-python#deprecation-of-old-package) and follow some [notes for referring to 2.x](https://github.com/quandl/quandl-python/blob/master/2_SERIES_UPGRADE.md).

If you are starting a new project we recommend you start python 3.  We also recommend you try to upgrade to python 3 as 2.7 has reached end-of-life; we no longer support it.

Installing our package is best handled through pip.  It will help resolve all dependencies for your environment.  We also recommend you setup [virtual-env](https://virtualenv.pypa.io/en/latest/) or [pipenv](https://docs.python-guide.org/dev/virtualenvs/) to help avoid polluting your system.

**Comment by couture-ql** [comment]
If you're still having issues, please reach out to connect@quandl.com.  Our support team will be glad to assist.
