### ISSUE TITLE
TypeError on API example

### ISSUE THREAD

**Issue by mrecachinas** [quandl/quandl-python#89]
# Environment

- macOS 10.12.4
- Issue occurs on Python 2.7.12 and 3.6.0
- quandl version 3.1.0

# Issue

Trying to run the `mydata = quandl.get("WIKI/AAPL", rows=5)` example from https://www.quandl.com/tools/python, but running into the following `TypeError`:

# Example

```python
➜  ~ python
Python 2.7.12 (default, Jun 29 2016, 14:05:02)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import quandl
>>> quandl.get("WIKI/AAPL", rows=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/quandl/get.py", line 48, in get
    data = Dataset(dataset_args['code']).data(params=kwargs, handle_column_not_found=True)
  File "/usr/local/lib/python2.7/site-packages/quandl/model/dataset.py", line 47, in data
    return Data.all(**updated_options)
  File "/usr/local/lib/python2.7/site-packages/quandl/operations/list.py", line 17, in all
    resource = cls.create_list_from_response(response_data)
  File "/usr/local/lib/python2.7/site-packages/quandl/operations/data_list.py", line 13, in create_list_from_response
    return DataList(cls, values, metadata)
  File "/usr/local/lib/python2.7/site-packages/quandl/model/model_list.py", line 14, in __init__
    converted_column_names = Util.convert_column_names(meta)
  File "/usr/local/lib/python2.7/site-packages/quandl/util.py", line 102, in convert_column_names
    the_list = [Util.methodize(x) for x in meta['column_names']]
  File "/usr/local/lib/python2.7/site-packages/quandl/util.py", line 26, in methodize
    return parameterize(string.replace(r'.', '')).replace(r'-', '_')
TypeError: an integer is required
```

The other examples (not involving `"WIKI/*"`) seem to be working.

**Comment by mrecachinas** [comment]
Fixed by updating `numpy`.
